### ISSUE TITLE
buildHeaderParam fails if data string contains double width unicode char

### ISSUE THREAD

**Issue by andrewtamura** [nodemailer/libmime#4] opened 2015-06-06 00:19 UTC
See PR https://github.com/andris9/libmime/pull/3 for a test case.

**Comment by andris9** [comment] 2015-06-07 15:57
Yes, I checked and it definitely is a bug. This is caused by encodeURIComponent that encodes characters not as a full string but one character at a time. I'll try to think something out.

**Comment by andrewtamura** [comment] 2015-06-08 19:27
thanks!

**Comment by andris9** [comment] 2016-08-24 07:57
I think this got fixed a long time ago. Closing

**Closed by andris9** 2016-08-24 07:57 UTC
